name: run jd-sign
on:
  push:
  schedule:
    - cron: '0 21 * * *'
jobs:
  sign:
    name: sign-jd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm start
        env:
          mycookie: ${{ secrets.MY_COOKIE }}
